#!/bin/bash

sum=0
for (( arv=1; arv<11; arv++ ))
do 
	jaak=$(($arv % 2))
	if [ $jaak -eq 0 ]; then
		summa=$(($summa + $arv))
		echo $summa
	fi
done
echo "vahemikus 1-10(kaasaarvatud) paarisarvude summa on: $summa"
