#!/bin/bash

echo -e "Sisesta tund 24h formaadis: \c"
read aeg
if [ $aeg -ge 6 -a $aeg -le 12 ] ; then
	echo "Gm Kanye"
elif [ $aeg -ge 12 -a $aeg -le 18 ] ; then
	echo "Gd Kanye"
elif [ $aeg -ge 18 -a $aeg -le 22 ] ; then
	echo "Ge Kanye"
elif [ $aeg -ge 22 -a $aeg -le 24 ] || [ $aeg -ge 0 -a $aeg -le 6 ] ; then
	echo "Gn Kanye"
else
	echo "Õpi kell ära"
fi


