#!/bin/bash

echo -e "Sisesta tund 24h formaadis: \c"
read aeg
user=$(whoami)
if [ $aeg -ge 6 -a $aeg -le 12 ] ; then
	echo "Gm $user"
elif [ $aeg -ge 12 -a $aeg -le 18 ] ; then
	echo "Gd $user"
elif [ $aeg -ge 18 -a $aeg -le 22 ] ; then
	echo "Ge $user"
elif [ $aeg -ge 22 -a $aeg -le 24 ] || [ $aeg -ge 0 -a $aeg -le 6 ] ; then
	echo "Gn $user"
else
	echo "Õpi kell ära"
fi


