#!/bin/bash

echo "Mitu reisjat on bussis: "
read  reisjad
echo "Mis on kohtade arv bussis: " 
read  kohad
bussid=`echo "scale=0;$reisjad / $kohad" | bc`
mahajaanud=`echo "scale=0;$reisjad % $kohad" | bc`
echo "Busse täidetud: $bussid"
echo "Maha jäänuid: $mahajaanud"
